# MongoDB connection settings
spring.data.mongodb.uri=mongodb+srv://todo_app_db:<pass>@cluster0.7yrett3.mongodb.net/jwt_auth_db?retryWrites=true&w=majority

# JWT configurations
app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwtExpirationMs=86400000

# Server port (Matches Flutter config.dart port 3000)
server.port=3000
