// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMIhecLW7KegL9dp6o_Ovu29motaK-6G0',
    appId: '1:391156030941:web:16d6c1758107ae92216a34',
    messagingSenderId: '391156030941',
    projectId: 'lab04-70e56',
    authDomain: 'lab04-70e56.firebaseapp.com',
    storageBucket: 'lab04-70e56.firebasestorage.app',
    measurementId: 'G-93YV6H1Q6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_J-bMMOZC4sStrbApBvnY4mB-Lcq2ZXw',
    appId: '1:391156030941:android:a69feb91ee7c8b45216a34',
    messagingSenderId: '391156030941',
    projectId: 'lab04-70e56',
    storageBucket: 'lab04-70e56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_HbdsX5w8AlJEDdw9NWHYTXQSiVIUg6I',
    appId: '1:391156030941:ios:e8dd67e6b55c6b58216a34',
    messagingSenderId: '391156030941',
    projectId: 'lab04-70e56',
    storageBucket: 'lab04-70e56.firebasestorage.app',
    androidClientId: '391156030941-456o0qhkcdbe3q1cp0jt1h8cvfum71f1.apps.googleusercontent.com',
    iosClientId: '391156030941-ulu1oug34e42gq2tbplugbo9c5vl9n0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_HbdsX5w8AlJEDdw9NWHYTXQSiVIUg6I',
    appId: '1:391156030941:ios:e8dd67e6b55c6b58216a34',
    messagingSenderId: '391156030941',
    projectId: 'lab04-70e56',
    storageBucket: 'lab04-70e56.firebasestorage.app',
    androidClientId: '391156030941-456o0qhkcdbe3q1cp0jt1h8cvfum71f1.apps.googleusercontent.com',
    iosClientId: '391156030941-ulu1oug34e42gq2tbplugbo9c5vl9n0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMIhecLW7KegL9dp6o_Ovu29motaK-6G0',
    appId: '1:391156030941:web:224a7313292926d3216a34',
    messagingSenderId: '391156030941',
    projectId: 'lab04-70e56',
    authDomain: 'lab04-70e56.firebaseapp.com',
    storageBucket: 'lab04-70e56.firebasestorage.app',
    measurementId: 'G-QKNMN7SLP4',
  );
}
